server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
         uri: https://github.com/YiHengLin/spring-cloud-demo.git
         searchPaths: spring-cloud-config
         #uri: file://D:/Henry/spring-cloud-config